site_name: Development & Security
site_description: >-
  Source of insight, pointers on cybersecurity and clean code practices. 
site_url: https://www.archive.robertovallado.dev/
site_author: Roberto Vallado

nav:
  - Home: index.md
  - Tags: tags.md
  - Knowledgebase:
    - journal/index.md
    - journal/tags.md
  - AEC:
    - aec/index.md
    - aec/tags.md
  - Archive:
    - archive/index.md
    - archive/tags.md
  - lexicon.md
  - about.md

theme:
  name: material
  language: en 
  custom_dir: overrides

  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  logo: assets/images/code.ico
  favicon: assets/images/code.ico
  font:
    text: Arial
    code: Roboto Mono

  palette:
    - scheme: slate        # Light mode
      primary: black
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - scheme: default          # Dark mode
      primary: black
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Light mode

plugins:
  - blog:
      blog_dir: journal
      post_dir: "journal/posts"
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Technical Interview Topics
        - éditorial
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10

  - blog:
      blog_dir: aec
      post_dir: "aec/posts"
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - AEC
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10

  - blog:
      blog_dir: archive
      post_dir: "archive/posts"
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Vault
      authors_profiles: true
      pagination_per_page: 10
      archive_pagination_per_page: 15
      categories_pagination_per_page: 15

      # post_slugify: !!python/object/apply:../ext.slugs.slugify  
      # TODO REVIEW - Keep commented until path is correct.
  - meta
  - tags

  # - i18n:
  #     docs_structure: folder
  #     default_language: en
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #         build: true
  #       - locale: fr
  #         name: Français
  #         default: false
  #         build: true
  #       - locale: es
  #         name: Español
  #         default: false
  #         build: true 
  # extra:
  #   languages:
  #     en:
  #       name: English
  #       link: /
  #     fr:
  #       name: Français
  #       link: /fr/
  #     es:
  #       name: Español
  #       link: /es/
  # Setting up multi-language installations WIP https://github.com/squidfunk/mkdocs-material/discussions/2346

  - search
  - mermaid2
  - macros

  - rss:
      match_path: "journal/posts/.*"
      date_from_meta:
        as_creation: date
        as_update: date_updated

  - rss:
      match_path: "aec/posts/.*"
      date_from_meta:
        as_creation: date
        as_update: date_updated
      
  - rss:
      match_path: "archive/posts/.*"
      date_from_meta:
        as_creation: date
        as_update: date_updated

draft_docs: |
  drafts/ 

#   social:
#     - icon: fontawesome/brands/github
#       name: Github
#       link: https://github.com/RobertoVallado

#     - icon: fontawesome/brands/linkedin
#       name: LinkedIn
#       link: https://www.linkedin.com/in/roberto-vallado/

#   generator: false  # hides the “Made with Material for MkDocs” text
# copyright: © <span id="year"></span> - Roberto Vallado's Dev & Security Journal.

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  - stylesheets/styles.css
  - stylesheets/home-background.css

extra_javascript:
  - assets/js/footer-year.js

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
